apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-8l0w
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-8l0w
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-8l0w
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-8l0w
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-8l0w
    spec:
      containers:
      - image: quay.io/rh-gitops-bot/rhtap-demo-ycaj-tenant/rhtap-demo-app/hacbs-test-project-8l0w@sha256:ec67362fa912ca7bd2984749384f831ed423fe5cdc32b65e97fda7183aa115ba
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
